server:
  port: 5999  # 서버 포트

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/mydb
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: com.example.JAVA_MES_API.dto
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true  # DB 컬럼명 → CamelCase 매핑

logging:
  level:
    org.mybatis: DEBUG
    com.example: DEBUG

jpa:
  hibernate:
    ddl-auto: update  # 개발 단계: update, 초기: create, 운영: validate or none
  show-sql: true
  properties:
    hibernate:
      format_sql: true

jwt:
  secret: ${JWT_SECRET}

fcm:
  project-id: mesfirebase-8169a
  service-account-path: src/main/resources/mesfirebase-8169a-20ed10ada5de.json

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
