spring.config.import: optional:file:.env

server:
  port: 5999  # ì„œë²„ í¬íŠ¸

spring:
  datasource:
    url: "jdbc:mysql://${DB_HOST}:${DB_PORT}/fullter"
    username: "${DB_USER}"
    password: "${DB_PASS}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  kafka:
    bootstrap-servers: ${KAFKA_BROKER}

mybatis:
  type-aliases-package: "com.example.JAVA_MES_API.dto"
  mapper-locations: "classpath:mapper/**/*.xml"
  configuration:
    map-underscore-to-camel-case: true  # DB ì»¬ëŸ¼ëª… â†’ CamelCase ë§¤í•‘

logging:
  level:
    org.mybatis: DEBUG
    com.example: DEBUG

jpa:
  hibernate:
    ddl-auto: update  # ê°œë°œ ë‹¨ê³„: update, ì´ˆê¸°: create, ìš´ì˜: validate or none
  show-sql: true
  properties:
    hibernate:
      format_sql: true

jwt:
  secret: "${JWT_SECRET}"  # ğŸ” í™˜ê²½ë³€ìˆ˜ì—ì„œ ê°€ì ¸ì˜¤ê²Œ ë”°ì˜´í‘œ ì¶”ê°€

fcm:
  project-id: "mesfirebase-8169a"
  service-account-path: "src/main/resources/mesfirebase-8169a-20ed10ada5de.json"

springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    operationsSorter: method
